[tool.poetry]
name = "atacnet"
version = "0.1.6"
description = "Package for building co-accessibility networks from ATAC-seq data."
authors = ["RÃ©mi Trimbour <remi.trimbour@pasteur.fr>"]
packages = [{include = "atacnet"}]
license = "GPL-3.0-only"
readme = "README.md"


[tool.poetry.build]
script = "build.py"
generate-setup-file = true

[tool.poetry.dependencies]
python = ">=3.7,<3.13"
numpy = "^1.25.0"
pandas = "^2.1.1"
scikit-learn = "^1.3.1"
joblib = "^1.1.0"
scanpy = "^1.8.1"
rich = "^10.12.0"

[tool.poetry.dev-dependencies]
flake8 = "*"
pydocstyle = "*"
mypy = "*"
pre-commit = "*"
isort = "*"
black = { version="*", allow-prereleases = true }
pytest = "*"

[tool.black]
line-length = 100
target-version = ["py38"]
exclude = '''
(
  \.eggs
  | \.git
  | \.mypy_cache
  | \.pytest_cache
  | build
  | __pycache__
  | Examples
  | Figures
)
'''

[tool.isort]
include_trailing_comma = true
line_length = 100
multi_line_output = 3

[build-system]
requires = ["poetry>=0.12", "setuptools", "numpy"]
build-backend = "poetry.masonry.api"
